### ISSUE TITLE
4k resolution size issue

### ISSUE THREAD

**Issue by oni222** [Shinzaku/Points#15]
How can I scale up the plugin so it does not look extremely tiny in 4k resolution.

I tried /points config and I do not see an option in there to scale it up.

Thank you.

**Comment by Shinzaku** [comment]
Not available yet, but there are plans to have it available this month

Thanks,

On Jan 6, 2023, at 2:21 PM, oni222 ***@***.***> wrote:

﻿

How can I scale up the plugin so it does not look extremely tiny in 4k resolution.

I tried /points config and I do not see an option in there to scale it up.

Thank you.

**Comment by Shinzaku** [comment]
Feature added in latest version
