### ISSUE TITLE
XP TNL (Till next Level)

### ISSUE THREAD

**Issue by oni222** [Shinzaku/Points#19]
Can we please get an XP TNL (Till next Level) feature. So we don't need to do the math on how much XP we need to level up.

Thank you.

**Comment by Shinzaku** [comment]
Added in 2.0.10

**Comment by oni222** [comment]
I am using the latest version but I cannot see the option anywhere. Can you please help me find it?

**Comment by Shinzaku** [comment]
Under the config when editing tokens, you have to add the new tag somewhere
[TNL] is the new tag that displays that
