### ISSUE TITLE
Custom input for X, Y positions? 

### ISSUE THREAD

**Issue by Shellshock9001** [Shinzaku/Points#21]
Would you be able to include custom X, Y position inputs? This way I can move it exactly where I want it. Thank you. For now I have to go to the addon file itself and adjust custom x, y from there.

**Comment by Shellshock9001** [comment]
also how could we add an inv string message to the UI output. it currently just shows 15/30. If it could show Inv: 15/30 and how would I rearrange the Gil message? its currently 100,000 G but I would like it to be G 100,000. Everything else has the token tag first and then the number except for Gil being on the right. Thank you for all these sweet updates

**Comment by Shinzaku** [comment]
Type in /points config to be able to edit some of the properties
Should be able to adjust the X and Y of the compact bar that way
For the larger bar, click and drag

**Comment by Shellshock9001** [comment]
Oh yeah, it can do that but it will drag it by like 2-4 points. Doesn't let you drag point by point. so like for me I needed to be 35 to put it lined up exactly with the chat log. But the dragging couldn't do that so it would look off. I went in to the config file and changed it there. If it could be custom entered number in the addons UI.

**Comment by Shellshock9001** [comment]
what would also be sick is to be able to add a ffxi gil image for the gil tracking. So it would be the FFXI gil coin image 100,000

**Comment by Shinzaku** [comment]
Found a workaround - now in latest version
