### ISSUE TITLE
Feature Request - Tabs

### ISSUE THREAD

**Issue by brad43326** [Shinzaku/Points#22]
Could you add Tabs player has similar to Sparks

**Comment by Shinzaku** [comment]
By tabs do you mean from fields/grounds of valor tomes? If so, I can slot that as a future enhancement

**Comment by Shinzaku** [comment]
After further review, this would be difficult to keep track of
The other currencies related to a player (Conquest Points, Crystals Stored, Bayld, Tabs, etc) are only retrieved in memory once a player opens up the Currencies or Currencies 2 menus. Either that, or when talking to an applicable NPC that uses up those currencies.
So until a player activates one of those menus, the values will always read as 0.
