### ISSUE TITLE
Unable to change tokens in /points config menu

### ISSUE THREAD

**Issue by rotyler** [Shinzaku/Points#25]
Whenever I try to change the text in the token editor textboxes, any changes I make are instantly reverted the instant i click anything outside of the textbox...

the settings menu:
![image](https://user-images.githubusercontent.com/45275744/217731120-9e9786de-3dc4-40cc-b495-9d82cacb37b0.png)

I try to change something:
![image](https://user-images.githubusercontent.com/45275744/217731234-4d600e8f-fc2c-4801-a9c8-3799af0a2a1c.png)

and i click literally anything on the menu popup window and it reverts:
![image](https://user-images.githubusercontent.com/45275744/217731315-d77f95a9-3c3c-4dbd-b879-7c1f96a608c1.png)

im no expert, but it's like the files are read only or something, like these textboxes are just for show...

**Comment by Shinzaku** [comment]
Latest version has overhauled the token editor - please try it out and let me know if you are still seeing issues

**Comment by rotyler** [comment]
Is 2.1.1 not the latest version? thats what I have currently (and the version this problem is happening on)

**Comment by Shinzaku** [comment]
Although the screenshot shows 2.1.1 (which is latest), it looks like you're using an old config setup. I'd recommend redownloading the entire zip to make sure all of the files in your addon folder are updated

**Comment by rotyler** [comment]
A full reinstall worked! I think I might not have replaced config.lua last time I updated... cause I thought it had my config saved there.... oops.
