### ISSUE TITLE
Feature Request - Option to display both job and subjob

### ISSUE THREAD

**Issue by AzrielltheWise** [Shinzaku/Points#28]
The ability to display JOB/SUB instead of just JOB on the bar would be incredibly helpful to quickly verify you have the correct sub.  I find myself accidentally /BLM more often than I care to admit when heading to events, and this feature would help remedy this.

**Comment by Shinzaku** [comment]
Unfortunately, the job listings are premade textures for this tool. They're not plain text.
I'd have to reformat the bar and edit the textures to fit them.

May consider for a future enhancement.
