### ISSUE TITLE
config\imgui.ini written to disk very frequently

### ISSUE THREAD

**Issue by zombie343** [Shinzaku/Points#30]
Hello!
   I noticed that imgui.ini is updated in it's entirety and written to disk very frequently (~3 times / second). Is it possible to change this behavior? Instead, could the file be updated when zoning or via a separate command? Any optimizations that helps prolong the life of my hardware is greatly appreciated. I did take a look at ashita/libs/imgui.lua and lib/settings, but I couldn't figure out where this continuous write is taking place.

**Comment by Shinzaku** [comment]
Hi,
I believe this is due to imgui itself, and would need the implementation itself updated

**Comment by Shinzaku** [comment]
Reopening due to possiblity it is Points - checking

**Comment by Shinzaku** [comment]
Fixed in 2.2.6
