### ISSUE TITLE
Feature Request - Estimated Time to Level (ETL)

### ISSUE THREAD

**Issue by trendcollective** [Shinzaku/Points#31]
Points is the best tracker by far, however, I used to use an older addon called Expmon and it had a stat called "ETL" or Estimated Time to Next Level. It would show you in hours, minutes and seconds how long it would be until you level up and was dynamic to your current Exp Per Hour and TNL amount. Would you consider adding an ETL or TNL Timer to Points?

**Comment by Shinzaku** [comment]
Points has a TNL tag that shows remaining EXP for the level. Although it doesn't calculate the estimated time, I will consider that for a future update.
