### ISSUE TITLE
points.lua:898: GetLimitMode() is nil

### ISSUE THREAD

**Issue by lenonk** [Shinzaku/Points#4]
Hi, on lines 898, 922, and 935, you call player:GetLimitMode() and check that it's value is greater than 96.  This fails for jobs < 99 (for jobs == 99 the if statement is short circuited and GetLimitMode() is never called).

Regardless, in Ashita v4, GetLimitMode() is nil.  I think what you want here is player:GetIsLimitModeEnabled().

Thanks!

**Comment by Shinzaku** [comment]
Fixed in 1.0.4

Thanks!
