### ISSUE TITLE
Merit points do not always update properly

### ISSUE THREAD

**Issue by lenonk** [Shinzaku/Points#6]
Hey, this is The Mystic from discord.  As you can see in the screen shot, LP: stopped updating at Merit point 7, and won't start updating again until I spend merit points, or some other unknown trigger happens.  Not sure what's going on.  If I can help you debug it, hit me up on Discord.
![Screenshot_20220112_183315](https://user-images.githubusercontent.com/1181733/149244948-9c6fc243-b8bc-4129-a25b-46e98feffdc1.png)

**Comment by Shinzaku** [comment]
Can you verify your version and if on retail? Latest release is 1.0.6. Should show version when addon is loaded.
Could you also list which zones this is happening, and on which jobs?

Thanks

**Comment by lenonk** [comment]
I'm on version 1.0.6.  I have confirmed that it happens in Escha - Ru'Aun, and Escha - Zi'tah, on RDM, DNC, DRK, and THF.

**Comment by Shinzaku** [comment]
Do you have any other addons that may be looking at merits?

**Comment by lenonk** [comment]
That's a *good* question.  I don't think so...

/addon load allmaps
/addon load blumon
/addon load enternity
/addon load imguistyle
/addon load macrofix
/addon load mapdot
/addon load sexchange
/addon load checker
/addon load filterscan
/addon load move
/addon load drawdistance
/addon load distance
/addon load fps
/addon load timestamp
/addon load tparty

/addon load trustee
/addon load macrochanger
/addon load autora
/addon load points
/addon load debuffed

**Comment by lenonk** [comment]
Also I just noticed in that screenshot that Accolades are 0?  I currently have 99999.  Probably not related but might have the same root cause I suppose.

**Comment by Shinzaku** [comment]
It looks like GetMeritPoints() and GetUnityPoints() aren't always returning accurate values - I guess it depends on whether or not the client has requested those values since zoning
Working on a side solution

**Comment by Shinzaku** [comment]
Tentative fix in 1.1.0
