### ISSUE TITLE
Crash on master lv up

### ISSUE THREAD

**Issue by GetAwayCoxn** [Shinzaku/Points#8]
Lv'd up to master lv 5 in ambu and points crashed. Screenshot attached, not much more info I'm sorry, I am using 1.1.0 from earlier today.

![Igotudis_2022 01 13_150656](https://user-images.githubusercontent.com/66495755/149409450-617d1ee9-a5ea-440c-aa2b-4b24165985bc.png)

**Comment by GetAwayCoxn** [comment]
appears to be happening on any kind of lv up, can verify job point and merit point attainment caused same crash

**Comment by Shinzaku** [comment]
Fixed on 1.1.1
