### ISSUE TITLE
Crash on abyssea status

### ISSUE THREAD

**Issue by GetAwayCoxn** [Shinzaku/Points#9]
Got a stack error crash as soon as I received abyssea status
Can reload ok but if I heal to update it will crash again same way, I am on 1.1.1.

![Igotudis_2022 01 15_112122](https://user-images.githubusercontent.com/66495755/149631344-9c7b3e03-9606-4f52-b51d-eb0d6c04e5d3.png)

**Comment by Shinzaku** [comment]
Fixed for 1.1.3
